POST http://localhost:5000/login 
content-type: application/json

{
    "email":"hi@hi.de",
    "password": "123456",
    "stayLogged": true
}

###

POST http://localhost:5000/register
content-type: application/json

{
    "email":"hi@hi.de",
    "password": "123456",
    "username": "Hifive"
}
### create Item without parent /isRoot

POST http://localhost:5000/createItem
content-type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTg5Mzc3M2EwNjI2M2UyMGM1YjhiZDgiLCJpYXQiOjE2MzY1MzQxMTgsImV4cCI6MTYzNzEzODkxOH0.Xcn_LXci6aabQoVbeEYZMUJtWgBKf2-PsYGn3eYDG6o

{
    "name":"targetworld",
    "description": "hey whats up?",
    "isRoot": true
}

### create Item with parent

POST http://localhost:5000/createItem
content-type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTg5Mzc3M2EwNjI2M2UyMGM1YjhiZDgiLCJpYXQiOjE2MzY1MzQxMTgsImV4cCI6MTYzNzEzODkxOH0.Xcn_LXci6aabQoVbeEYZMUJtWgBKf2-PsYGn3eYDG6o

{
    "name":"testworld child",
    "description": "hey whats up?",
    "parentId": "618cddfe5fb95660b6e3886b"
}

###

GET http://localhost:5000/getItem
content-type: application/json
Authorization: Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTg5Mzc3M2EwNjI2M2UyMGM1YjhiZDgiLCJpYXQiOjE2MzY1MzQxMTgsImV4cCI6MTYzNzEzODkxOH0.Xcn_LXci6aabQoVbeEYZMUJtWgBKf2-PsYGn3eYDG6o

{
    "isRoot": true
}